kind: Service
apiVersion: v1
metadata:
  name: kafka-service
spec:
  selector:
   app: kafka-app
  ports:
   - protocol: TCP
     port: 9092
     targetPort: 9092
     name: idk
   - protocol: TCP
     port: 2181
     targetPort: 2181
     name: idk2